---
- hosts: webservers
  become: yes
  tasks:
    - name: Copy web app files
      copy:
        src: "{{ playbook_dir }}/../../"
        dest: /var/www/
        owner: www-data
        group: www-data
